# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|


  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  config.vm.provision "ansible" do |ansible|

    ansible.playbook = "test.yml"
    ansible.extra_vars = { 
      hosts: "dev"
    }
    ansible.groups = {
      "dev" => ["default"],
      "all_groups:children" => ["dev"]
    }

  end

end
